### ISSUE TITLE
Once DLL is put in Firefox Folder XPCOM error starts on startup

### ISSUE THREAD

**Issue by CitizenFoffie** [ephemeralViolette/firefox-native-controls#1]
![image](https://github.com/ephemeralViolette/firefox-native-controls/assets/40131823/14258be8-33aa-498c-bdf4-ac4076c0b611)

**Comment by ephemeralViolette** [comment]
You need to choose a different version or compile it for yourself. There is no solution other than that. `xul.dll` is locked to specific versions, and you might not have perfect luck with the precompiled versions.
